package com.nuvexa.app.ui.tools.developer

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Slider
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import com.nuvexa.app.R
import com.nuvexa.app.core.util.copyTextToClipboard
import com.nuvexa.app.ui.components.PrimaryButton
import com.nuvexa.app.ui.theme.LocalSpacing
import kotlin.random.Random

private val WORDS = ("lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut " +
    "labore et dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamco laboris nisi aliquip " +
    "ex ea commodo consequat duis aute irure in reprehenderit voluptate velit esse cillum eu fugiat nulla " +
    "pariatur excepteur sint occaecat cupidatat non proident sunt culpa qui officia deserunt mollit anim id est")
    .split(" ")

private fun randomParagraph(sentenceCount: Int): String {
    val sentences = (1..sentenceCount).map {
        val length = Random.nextInt(8, 16)
        val words = (1..length).map { WORDS.random() }
        words.joinToString(" ").replaceFirstChar { it.uppercase() } + "."
    }
    return sentences.joinToString(" ")
}

@Composable
fun LoremIpsumScreen(modifier: Modifier = Modifier) {
    val spacing = LocalSpacing.current
    val context = LocalContext.current
    var paragraphCount by remember { mutableStateOf(3f) }
    var generated by remember { mutableStateOf(listOf(randomParagraph(5))) }

    Column(modifier = modifier.fillMaxWidth(), verticalArrangement = Arrangement.spacedBy(spacing.l)) {
        Text(stringResource(R.string.lorem_paragraphs_label, paragraphCount.toInt()), style = MaterialTheme.typography.labelLarge)
        Slider(value = paragraphCount, onValueChange = { paragraphCount = it }, valueRange = 1f..10f, steps = 8)

        PrimaryButton(
            text = stringResource(R.string.action_generate),
            onClick = { generated = (1..paragraphCount.toInt()).map { randomParagraph(Random.nextInt(4, 7)) } },
            modifier = Modifier.fillMaxWidth(),
        )

        Column(verticalArrangement = Arrangement.spacedBy(spacing.m)) {
            generated.forEach { paragraph ->
                Text(paragraph, style = MaterialTheme.typography.bodyMedium)
            }
        }

        PrimaryButton(
            text = stringResource(R.string.action_copy),
            onClick = { context.copyTextToClipboard(generated.joinToString("\n\n")) },
            modifier = Modifier.fillMaxWidth(),
        )
    }
}
